# Copyright (c) 2016-2018 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Documentació del 1er Regiment Amfibi
site_description: Documentació del grup 1RA a la Comunitat Catalana de Simulació, Cavallers del Cel
site_author: Viper
site_url: http://arma.cavallersdelcel.cat

# Repository
repo_name: CavallersDelCel/1RA_docs
repo_url: https://github.com/CavallersDelCel/1RA_docs
edit_uri: "https://github.com/CavallersDelCel/1RA_docs/tree/master/docs"

# Copyright
copyright: 'Copyright &copy; 2010 - 2018 Cavallers del Cel'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: ca
  feature:
    tabs: false
  palette:
    primary: Brown
    accent: Deep Orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: _imatges/favicon.ico
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: http://cavallersdelcel.cat
    - type: github-alt
      link: https://github.com/CavallersDelCel
    - type: youtube
      link: http://www.youtube.com/user/cavallersdelcel
    - type: twitter
      link: http://twitter.com/CavallersdelCel
    - type: facebook
      link: http://www.facebook.com/cavallersdelcel
 
extra_css:
    - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
- Benvinguts: 'index.md'
- Guia pel nous:
    - 'Benvingut': 'gn/index.md'
    - 'Pas 1: Requisits tècnics': 'gn/pas1.md'
    - 'Pas 2: Fòrums': 'gn/pas2.md'
    - 'Pas 3: Discord': 'gn/pas3.md'
    - 'Pas 4: Funcionament': 'gn/pas4.md'
    - 'Pas 5: Perfil': 'gn/pas5.md'
    - 'Pas 6: Bootcamp': 'gn/pas6.md'
    - 'Pas 7: Descàrrega de mods': 'gn/pas7.md'
    - 'Pas 8: Instal·lació ACRE2': 'gn/pas8.md'
    - 'Pas 9: CIB': 'gn/pas9.md'
    - 'Pas 10: Primera missió': 'gn/pas10.md'
    - 'Ja ets tot un Marine': 'gn/marine.md'
    - 'Notes finals':
        - 'Crèdits': 'gn/notes/credits.md'
- Entrenament Bàsic de Combat:
    - 'Introducció': 'ebc/index.md'
    - 'Fase1 - Groga': 
        - 'Benvinguda': 'ebc/fase1/benvinguda.md'
        - 'Simulador': 'ebc/fase1/simulador.md'
    - 'Fase2 - Vermella':
        - 'Balística i fonaments de la punteria amb fusell': 'ebc/fase2/punteria1.md'
        - 'Regles de combat': 'ebc/fase2/rdc.md'
        - 'Navegació terrestre desmuntada': 'ebc/fase2/navegacio.md'
        - 'Camuflatge i ocultació': 'ebc/fase2/camuflatge.md'
        - 'Patrulla i formacions': 'ebc/fase2/patrulla.md'
    - 'Fase3 - Blanca':
        - 'Fonaments de la punteria amb fusell reforçats': 'ebc/fase3/punteria2.md'
        - 'Prioritzar i atacar objectius a diferents distàncies': 'ebc/fase3/prioritzar.md'
    - 'Fase4 - Blava':
        - 'Comunicacions': 'ebc/fase4/comunicacions.md'
        - 'Punteria avançada amb fusell': 'ebc/fase4/punteria3.md'
        - 'Maniobrar i atacar objectius com a part d’una esquadra': 'ebc/fase4/maniobrar.md'
        - 'Granades de fragmentació M67 i de fum M18': 'ebc/fase4/granades.md'
        - 'Emprar armes mes potents i de tripulació': 'ebc/fase4/armes_tripulacio.md'
        - 'Metralladora M240B': 'ebc/fase4/metralladores.md'
        - 'Fusell automàtic M249': 'ebc/fase4/fusell_auto.md'
        - 'Llançador antitanc AT4': 'ebc/fase4/antitanc.md'
        - 'Llançagranades de 40mm M203': 'ebc/fase4/llan_granades.md'
        - 'Operacions militars a terreny urbà (MOUT - Military Operations in Urban Terrain)': 'ebc/fase4/mout.md'
        - 'Defensa del comboi': 'ebc/fase4/comboi.md'
    - 'Notes finals':
        - 'Protocol operatiu de comunicació "POC"': 'ebc/notes/poc.md'
        - 'Bibliografia': 'ebc/notes/bibliografia.md'
        - 'Crèdits': 'ebc/notes/credits.md'
- Curs Recon Bàsic (WIP):
    - 'Sobre el CRB': 'crb/index.md'
    - 'Fase 1 - Introducció': 
        - '1.1. Història del grup': 'crb/fase1/historia.md'
        - '1.2. Equip recon': 'crb/fase1/equiprecon.md'
        - '1.3. Operacions': 'crb/fase1/operacions.md'
        - '1.4. Suports': 'crb/fase1/suports.md'
        - '1.5. Comunicacions': 'crb/fase1/comunicacions.md'
        - '1.6. Armament bàsic': 'crb/fase1/armamentbasic.md'
        - '1.7. Armament avançat': 'crb/fase1/armamentavançat.md'
        - '1.8. Demolicions i AT': 'crb/fase1/demolicions.md'
        - '1.9. Primers auxilis': 'crb/fase1/primersauxilis.md'
    - 'Fase 2 - Combat bàsic':
        - '2.1. Patrulles a peu': 'crb/fase2/patrullespeu.md'
        - '2.2. Maniobres bàsiques': 'crb/fase2/maniobresbasiques.md'
        - '2.3. Maniobres ofensives': 'crb/fase2/maniobresofensives.md'
        - '2.4. Maniobres defensives': 'crb/fase2/maniobresdefensives.md'
        - '2.5. Maniobres nocturnes': 'crb/fase2/maniobresnocturnes.md'
    - 'Fase 3 - Combat urbà':
        - '3.1. Informació sensible': 'crb/fase3/intel.md'
        - '3.2. Moviment urbà': 'crb/fase3/movimenturba.md'
        - '3.3. Combat proper': 'crb/fase3/cqb.md'
    - 'Fase 4 - Combat especialitzat':
        - '4.1. Comboi de vehicles': 'crb/fase4/comboi.md'
        - '4.2. Inserció amfibia': 'crb/fase4/insercioamfibia.md'
        - '4.3. Inserció aèria': 'crb/fase4/insercioaeria.md'
    - 'Fase 5 - Evasió i supervivència':
        - '5.1. Navegació avançada': 'crb/fase5/navegacio.md'
        - '5.2. Evasió': 'crb/fase5/teoricaevasio.md'
        - '5.3. Prova final': 'crb/fase5/provafinal.md'
    - 'Notes finals':
        - 'Bibliografia': 'crb/notes/bibliografia.md'
        - 'Crèdits': 'crb/notes/credits.md'
- Curs de Qualificació AT/AA:
    - 'Sobre el manual': 'cqataa/index.md'
    - 'Introducció': 
        - 'Introducció': 'cqataa/introduccio/introduccio.md'
        - 'Rols': 'cqataa/introduccio/rols.md'
        - 'Llança-coets vs Llança-missils': 'cqataa/introduccio/tipus.md'
    - 'Anti-blindatge': 
        - 'Fonaments anti-blindatge': 'cqataa/anti-blindatge/fonaments.md'
        - 'Tipus ogives': 'cqataa/anti-blindatge/ogives.md'
        - 'M136 AT-4': 'cqataa/anti-blindatge/at4.md'
        - 'M72 LAW': 'cqataa/anti-blindatge/m72.md'
        - 'M3 MAAWS (Carl Gustaf)': 'cqataa/anti-blindatge/carlgustaf.md'
        - 'Mk. 153 SMAW': 'cqataa/anti-blindatge/smaw.md'
        - 'FGM-148 Javelin': 'cqataa/anti-blindatge/javelin.md'
        - 'BGM-71 TOW': 'cqataa/anti-blindatge/tow.md'
        - 'RPG-7': 'cqataa/anti-blindatge/rpg.md'
    - 'Anti-aeri':
        - 'Fonaments anti-aeris': 'cqataa/anti-aeri/fonaments.md'
        - 'FIM-92 Stinger': 'cqataa/anti-aeri/stinger.md'
    - 'Notes finals':
        - 'Bibliografia': 'cqataa/notes/bibliografia.md'
        - 'Crèdits': 'cqataa/notes/credits.md'
- Curs d'Especialització en Franctirador:
    - 'Sobre el manual': 'cef/index.md'
    - 'Inici': 
        - 'Introducció': 'cef/inici/introduccio.md'
        - 'Tipus de tiradors': 'cef/inici/tipus.md'
        - 'El binomi de franctiradors': 'cef/inici/binomi.md'
    - 'Doctrina i Armament': 
        - 'Doctrina, moviment i camuflatge': 'cef/doctrina_i_armament/doctrina.md'
        - 'Armament': 'cef/doctrina_i_armament/armament.md'
    - 'Balística i Mires':
        - 'Balística avançada': 'cef/balistica/balistica.md'
        - 'Mires telescòpiques i zeroing': 'cef/balistica/mires.md'
    - 'Eines':
        - 'Taula de rangs': 'cef/eines/taularangs.md'
        - 'Telèmetre Vector 21': 'cef/eines/vector.md'
        - 'Kestrel 4500': 'cef/eines/kestrel.md'
        - 'Horus ATragMX': 'cef/eines/atragmx.md'
    - 'Mètodes':
        - 'Mètodes de tir': 'cef/metodes/metodestir.md'
    - 'Annexes':
        - 'ANNEX 1: Telescòpi portàtil': 'cef/annexes/annex1.md'
        - 'ANNEX 2: Tripode SSWT': 'cef/annexes/annex2.md'
        - 'ANNEX 3: Funda del fusell': 'cef/annexes/annex3.md'
        - 'ANNEX 4: Escala de Beaufort': 'cef/annexes/annex4.md'
        - 'ANNEX 5: Equipacions': 'cef/annexes/annex5.md'
    - 'Notes finals':
        - 'Bibliografia': 'cef/notes/bibliografia.md'
        - 'Crèdits': 'cef/notes/credits.md'


# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
